### ISSUE TITLE
Errors when running with ASSETS_DEBUG=True

### ISSUE THREAD

**Issue by blixhavn** [inveniosoftware/invenio-theme#33]
When trying to run my Invenio installation with `ASSETS_DEBUG=True`, I get an error complaining about missing output `BuildError: No output target found` from bundles.py:
```
js = Bundle(
    NpmBundle(
        'node_modules/almond/almond.js',
        'js/settings.js',
        filters='uglifyjs',
        npm={
            "almond": "~0.3.1",
            "jquery": "~1.9.1"
        }
    ),
    Bundle(
        'js/base.js',
        filters='requirejs',
       **** MISSING OUTPUT ****
    ),
    filters='jsmin',
    output="gen/packed.%(version)s.js",
)
```

When fixing this, I get (as @jalavik mentioned on Gitter yesterday) the following javascript error from almond.js:310: `Uncaught Error: undefined missing jquery`. I thought `ASSETS_DEBUG` was supposed to let require.js do the work? Does anyone know what's going on?

**Comment by jirikuncar** [comment]
@blixhavn can you reproduce it by running tests with `ASSETS_DEBUG=True`?

**Comment by blixhavn** [comment]
Ran `python setup.py test` with `ASSETS_DEBUG=True` both in the default config set in `ext.py` and in the config file of my current environment. All 23 tests passed.

**Comment by blixhavn** [comment]
- [ ] `assets clean` also not working btw. Traceback: 
```
▶ tind assets clean
Cleaning generated assets...
Traceback (most recent call last):
  File "/Users/blixhavn/.virtualenvs/invenio3/bin/tind", line 9, in <module>
    load_entry_point('tind==0.1.0.dev0', 'console_scripts', 'tind')()
  File "/Users/blixhavn/.virtualenvs/invenio3/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/Users/blixhavn/.virtualenvs/invenio3/lib/python2.7/site-packages/flask_cli/cli.py", line 343, in main
    return AppGroup.main(self, *args, **kwargs)
  File "/Users/blixhavn/.virtualenvs/invenio3/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/Users/blixhavn/.virtualenvs/invenio3/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/blixhavn/.virtualenvs/invenio3/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/blixhavn/.virtualenvs/invenio3/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/blixhavn/.virtualenvs/invenio3/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/Users/blixhavn/.virtualenvs/invenio3/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/blixhavn/.virtualenvs/invenio3/lib/python2.7/site-packages/flask_cli/cli.py", line 210, in decorator
    return __ctx.invoke(f, *args, **kwargs)
  File "/Users/blixhavn/.virtualenvs/invenio3/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/Users/blixhavn/.virtualenvs/invenio3/src/invenio-assets/invenio_assets/cli.py", line 113, in clean
    _webassets_cmd('clean')
  File "/Users/blixhavn/.virtualenvs/invenio3/src/invenio-assets/invenio_assets/cli.py", line 53, in _webassets_cmd
    getattr(cmdenv, cmd)()
  File "/Users/blixhavn/.virtualenvs/invenio3/lib/python2.7/site-packages/webassets/script.py", line 299, in __call__
    file_path = bundle.resolve_output(self.environment)
  File "/Users/blixhavn/.virtualenvs/invenio3/lib/python2.7/site-packages/webassets/bundle.py", line 326, in resolve_output
    output = ctx.resolver.resolve_output_to_path(ctx, self.output, self)
  File "/Users/blixhavn/.virtualenvs/invenio3/lib/python2.7/site-packages/flask_assets.py", line 201, in resolve_output_to_path
    directory, rel_path, endpoint = self.split_prefix(ctx, target)
  File "/Users/blixhavn/.virtualenvs/invenio3/lib/python2.7/site-packages/flask_assets.py", line 152, in split_prefix
    app = ctx.environment._app
AttributeError: 'Environment' object has no attribute 'environment'
```

**Comment by jirikuncar** [comment]
I can't reproduce it. Please re-open if you still encounter the problem. Thanks
